@baseURL = http://127.0.0.1:8000


@resourse = legal-person


###
# @name all

GET {{baseURL}}/api/{{resourse}}


###

# @name create

POST {{baseURL}}/api/{{resourse}}
Content-Type: application/json

{
    "name": "Empresa 5",
    "city_id": 1,
    "cnpj": "1238",
    "fantasy_name": "Empresa de teste 4"
}


###
# @name getOne

GET {{baseURL}}/api/{{resourse}}/1


###

# @name update

PUT  {{baseURL}}/api/{{resourse}}/2
Content-Type: application/json

{
    "cnpj": "1237"
}


###
# @name deleteOne

DELETE  {{baseURL}}/api/{{resourse}}/2
