@baseURL = http://127.0.0.1:8000


@resourse = packages


###
# @name all

GET {{baseURL}}/api/{{resourse}}


###

# @name create

POST {{baseURL}}/api/{{resourse}}
Content-Type: application/json

{
    "sender_id": 1,
    "destination_id": 1,
    "weight": 1.5,
    "volume": 5
}


###
# @name getOne

GET {{baseURL}}/api/{{resourse}}/1


###

# @name update

PUT  {{baseURL}}/api/{{resourse}}/1
Content-Type: application/json

{
    "delivery_state": 1
}


###
# @name deleteOne

DELETE  {{baseURL}}/api/{{resourse}}/2


###

# @name RegisterLog

POST {{baseURL}}/api/{{resourse}}/703671e5/log
Content-Type: application/json


{
    "city_id": 1
}