@baseURL = http://127.0.0.1:8000

###
# @name allStates

GET {{baseURL}}/api/states

###

# @name createState

POST {{baseURL}}/api/states
Content-Type: application/json

{
    "name": "Maranhão",
    "abbreviation": "MA"
}


###
# @name getOneState

GET {{baseURL}}/api/states/7


###
# @name deleteOneState

DELETE  {{baseURL}}/api/states/7


###

# @name updateOneState

PUT  {{baseURL}}/api/states/5
Content-Type: application/json

{
    "name": "PIAUI",
    "abbreviation": "GO"
}

